---
kind: pipeline
type: docker
name: build

trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
      - pull_request

steps:
  - name: build
    image: alpine/helm
    pull: always
    commands:
      - helm dependency update
      - helm package .

---
kind: pipeline
type: docker
name: release

depends_on:
  - build

trigger:
  event:
    - tag

steps:
  - name: build
    image: alpine/helm
    pull: always
    environment:
      HELM_PASSWORD:
        from_secret: helm_password
    commands:
      - helm dependency update
      - helm package .
      - curl --user "frederick:$HELM_PASSWORD" -X POST --upload-file vikunja-*.tgz https://kolaente.dev/api/packages/vikunja/helm/api/charts
---
kind: signature
hmac: 993135e828384d9938343750ed3164c2ae702b87118d28b74ae3e1f522403f61

...
