{{- if and .Values.api.persistence.enabled .Values.api.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vikunja.pvcName" . }}
  labels:
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.api.persistence.spec | nindent 2 }}
{{- end }}
